# generated by invokta-deploy v0 — do not edit; edits block regeneration
#
# Multi-stage build for an MCP Streamable HTTP engine. The build stage installs
# from the committed lockfile, runs the project build script, and prunes to
# production dependencies. The runtime stage carries only what the server runs.

FROM node:22-slim AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build
RUN npm ci --omit=dev

FROM node:22-slim AS runtime
ENV NODE_ENV=production
ENV INVOKTA_HTTP_HOST=0.0.0.0
ENV INVOKTA_HTTP_PORT=3000
WORKDIR /app
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/deploy/healthcheck.mjs ./deploy/healthcheck.mjs
USER node
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 CMD ["node", "deploy/healthcheck.mjs"]
CMD ["node", "dist/mcp-http.js"]
