/**
 * Environment file loading for this engine.
 *
 * Importing this module applies ./.env — or the file named by
 * INVOKTA_ENV_FILE — to the process environment exactly once, before any
 * other module reads configuration. A variable the real environment already
 * defines is never replaced, so a local file can never displace platform
 * configuration. Only names are ever reported; a value never reaches a
 * diagnostic.
 *
 * Generated by "invokta-deploy init". This file is yours to edit.
 */
import { lstatSync, readFileSync, type Stats } from "node:fs";
import { isAbsolute, resolve } from "node:path";
import { parseEnv } from "node:util";

/** One stable sentence per failure. None of them carries a value. */
export const environmentStartupMessages = Object.freeze({
  FILE_NOT_FOUND: "The configured environment file was not found.",
  FILE_UNSAFE: "The environment file is unsafe to load.",
  FILE_UNPARSABLE: "The environment file could not be parsed.",
  NAME_INVALID: "The environment file contains an invalid variable name.",
  LIMIT_EXCEEDED: "The environment file exceeds a load limit.",
  REQUIRED_MISSING: "A required environment variable is missing.",
} as const);

export const environmentLoadLimits = Object.freeze({
  maxFileBytes: 65_536,
  maxAppliedKeys: 256,
  maxValueScalars: 4_096,
} as const);

const environmentNamePattern = /^[A-Z_][A-Z0-9_]{0,127}$/;
const overrideVariableName = "INVOKTA_ENV_FILE";
const defaultFileName = ".env";
const nulCharacter = "\u0000";
const decoder = new TextDecoder("utf-8", { fatal: true });

export type EnvironmentRecord = Record<string, string | undefined>;

export interface EnvironmentLoadOptions {
  /** Defaults to the process environment. */
  readonly env?: EnvironmentRecord;
  /** Defaults to the process working directory. */
  readonly cwd?: string;
}

/**
 * A startup failure of this composition root. The message is one stable
 * sentence, optionally followed by names — never a value, file content, stack
 * trace, or cause chain.
 */
export class EngineStartupError extends Error {
  constructor(message: string, detail?: string) {
    super(detail === undefined ? message : `${message} (${detail})`);
    this.name = "EngineStartupError";
  }
}

interface EnvironmentFileTarget {
  readonly path: string;
  /** True when INVOKTA_ENV_FILE named the file, which forbids degrading. */
  readonly explicit: boolean;
}

function countScalars(value: string): number {
  let count = 0;
  for (const _ of value) count += 1;
  return count;
}

function readErrorCode(error: unknown): string | undefined {
  if (typeof error !== "object" || error === null) return undefined;
  const code = (error as { readonly code?: unknown }).code;
  return typeof code === "string" ? code : undefined;
}

function unsafeFile(target: EnvironmentFileTarget): EngineStartupError {
  return new EngineStartupError(
    environmentStartupMessages.FILE_UNSAFE,
    target.path,
  );
}

function missingFile(target: EnvironmentFileTarget): EngineStartupError {
  return new EngineStartupError(
    environmentStartupMessages.FILE_NOT_FOUND,
    target.path,
  );
}

function resolveTarget(
  environment: EnvironmentRecord,
  workingDirectory: string,
): EnvironmentFileTarget {
  const override = environment[overrideVariableName];
  if (override === undefined || override === "") {
    return {
      path: resolve(workingDirectory, defaultFileName),
      explicit: false,
    };
  }
  if (override.includes(nulCharacter)) {
    throw new EngineStartupError(environmentStartupMessages.FILE_UNSAFE);
  }
  return {
    path: isAbsolute(override) ? override : resolve(workingDirectory, override),
    explicit: true,
  };
}

/** Returns the file status, or undefined when an optional default is absent. */
function statTarget(target: EnvironmentFileTarget): Stats | undefined {
  try {
    // lstat, never stat: a symlink is refused rather than followed, so the
    // file that is checked is always the file that is read.
    return lstatSync(target.path);
  } catch (error) {
    const code = readErrorCode(error);
    const absent = code === "ENOENT" || code === "ENOTDIR";
    if (absent && !target.explicit) return undefined;
    throw absent ? missingFile(target) : unsafeFile(target);
  }
}

/** Returns the file text, or undefined when an optional default is absent. */
function readTarget(target: EnvironmentFileTarget): string | undefined {
  const status = statTarget(target);
  if (status === undefined) return undefined;

  if (status.isSymbolicLink()) throw unsafeFile(target);
  if (!status.isFile()) {
    throw target.explicit ? missingFile(target) : unsafeFile(target);
  }
  if (status.size > environmentLoadLimits.maxFileBytes) {
    throw unsafeFile(target);
  }

  let contents: Buffer;
  try {
    contents = readFileSync(target.path);
  } catch {
    throw unsafeFile(target);
  }
  if (contents.length > environmentLoadLimits.maxFileBytes) {
    throw unsafeFile(target);
  }
  // A NUL byte marks the file as something other than the text this parser
  // accepts, whatever produced it.
  if (contents.includes(0)) throw unsafeFile(target);
  try {
    return decoder.decode(contents);
  } catch {
    throw unsafeFile(target);
  }
}

/**
 * Applies one environment file to the environment. Absent keys only, so
 * precedence is fixed: process environment, then environment file, then this
 * composition root's own defaults.
 */
export function loadEnvironmentFile(
  options: EnvironmentLoadOptions = {},
): void {
  const environment: EnvironmentRecord = options.env ?? process.env;
  const target = resolveTarget(environment, options.cwd ?? process.cwd());
  const contents = readTarget(target);
  if (contents === undefined) return;

  let parsed: NodeJS.Dict<string>;
  try {
    // The dialect is the platform parser's, never a local reimplementation.
    parsed = parseEnv(contents);
  } catch {
    throw new EngineStartupError(
      environmentStartupMessages.FILE_UNPARSABLE,
      target.path,
    );
  }

  // A key the environment already defines — including with an empty value —
  // is never replaced, so it is also exempt from the name check below.
  const applicable = Object.keys(parsed).filter(
    (key) => environment[key] === undefined,
  );
  if (applicable.length > environmentLoadLimits.maxAppliedKeys) {
    throw new EngineStartupError(
      environmentStartupMessages.LIMIT_EXCEEDED,
      `applied keys: ${applicable.length}`,
    );
  }
  for (const key of applicable) {
    if (!environmentNamePattern.test(key)) {
      throw new EngineStartupError(
        environmentStartupMessages.NAME_INVALID,
        key,
      );
    }
    const scalars = countScalars(parsed[key] ?? "");
    if (scalars > environmentLoadLimits.maxValueScalars) {
      throw new EngineStartupError(
        environmentStartupMessages.LIMIT_EXCEEDED,
        `${key}: ${scalars} scalar values`,
      );
    }
  }

  // Nothing is applied until every key and value has passed its check.
  for (const key of applicable) {
    const value = parsed[key];
    if (value !== undefined) environment[key] = value;
  }
}

/**
 * Verifies that every declared name is present and non-empty. Presence is not
 * validity: semantic checks belong to the adapter options, the capability
 * input schemas, and the authentication hook.
 */
export function requireEnvironment(
  names: readonly string[],
  options: EnvironmentLoadOptions = {},
): void {
  const environment: EnvironmentRecord = options.env ?? process.env;
  const missing = names.filter((name) => {
    const value = environment[name];
    return value === undefined || value === "";
  });
  if (missing.length === 0) return;
  throw new EngineStartupError(
    environmentStartupMessages.REQUIRED_MISSING,
    missing.join(", "),
  );
}

/**
 * Writes one sanitized line to stderr and stops the process. An unexpected
 * error is reported without its own message, so nothing a dependency placed
 * in it can reach a log.
 */
export function reportStartupFailure(error: unknown): never {
  const message =
    error instanceof EngineStartupError
      ? error.message
      : "The engine failed to start.";
  process.stderr.write(`${message}\n`);
  process.exit(1);
}

// Loading happens on import so that no module can read configuration before
// the file has been applied. It is the only side effect of this module.
try {
  loadEnvironmentFile();
} catch (error) {
  reportStartupFailure(error);
}
