/**
 * Authentication hook for the MCP HTTP composition root.
 *
 * Uses Better Auth as the OAuth 2.1 authorization server and token issuer.
 * The adapter calls authenticate() for every request that passes the Host and
 * Origin checks. Verifies incoming JWT access tokens using Better Auth's JWKS
 * or secret key, and returns the proved Principal, or null to answer with an
 * HTTP 401 Bearer challenge pointing to the Protected Resource Metadata.
 *
 * Generated by "invokta-deploy init". This file is yours to edit.
 */
import type {
  McpHttpAuthOptions,
  McpHttpAuthenticationRequest,
  McpHttpProtectedResourceMetadata,
} from "@invokta/mcp";
import type { Principal } from "@invokta/core";
import { createRemoteJWKSet, jwtVerify, type JWTVerifyGetKey } from "jose";

import { EngineStartupError } from "./env.js";

type RequiredMcpHttpAuth = Extract<
  McpHttpAuthOptions,
  { readonly mode: "required" }
>;

export interface HttpAuthOptions {
  /** The base URL of the Better Auth authorization server (e.g. https://auth.example.com or http://127.0.0.1:4000). */
  readonly authServerUrl: string;
  /** The public URL of this MCP endpoint (e.g. https://api.example.com/mcp or http://127.0.0.1:3000/mcp). */
  readonly resourceUrl: string;
  /** Optional custom JWKS endpoint URL. Defaults to ${authServerUrl}/api/auth/jwks */
  readonly jwksUri?: string;
  /** Optional secret for symmetric token verification (e.g. BETTER_AUTH_SECRET). */
  readonly secret?: string;
  /** Optional scopes supported by this MCP server. */
  readonly supportedScopes?: readonly string[];
  /** Optional custom token verifier (for testing or specialized custom validation). */
  readonly verifyToken?: (token: string) => Promise<Principal | null>;
}

const defaultSupportedScopes = Object.freeze(["nota-fiscal"]);

function normalizeUrl(value: string, fieldName: string): URL {
  try {
    const url = new URL(value);
    if (url.protocol !== "http:" && url.protocol !== "https:") {
      throw new EngineStartupError(`${fieldName} must use http or https protocol.`);
    }
    return url;
  } catch (error) {
    if (error instanceof EngineStartupError) throw error;
    throw new EngineStartupError(`${fieldName} is not a valid URL.`);
  }
}

/**
 * Creates fail-closed OAuth 2.1 authentication for the MCP HTTP endpoint
 * backed by Better Auth.
 */
export function createHttpAuth(options: HttpAuthOptions): RequiredMcpHttpAuth {
  if (!options.authServerUrl) {
    throw new EngineStartupError("BETTER_AUTH_URL is required.");
  }
  if (!options.resourceUrl) {
    throw new EngineStartupError("MCP_RESOURCE_URL is required.");
  }

  const authServer = normalizeUrl(options.authServerUrl, "BETTER_AUTH_URL");
  normalizeUrl(options.resourceUrl, "MCP_RESOURCE_URL");

  const resolvedJwksUri =
    options.jwksUri ?? `${authServer.origin}/api/auth/jwks`;

  let remoteJwks: JWTVerifyGetKey | undefined;
  if (!options.secret && !options.verifyToken) {
    const jwksUrl = normalizeUrl(resolvedJwksUri, "BETTER_AUTH_JWKS_URL");
    remoteJwks = createRemoteJWKSet(jwksUrl);
  }

  const supportedScopes = options.supportedScopes ?? defaultSupportedScopes;

  async function verifyJwt(token: string): Promise<Principal | null> {
    try {
      if (options.verifyToken) {
        return await options.verifyToken(token);
      }

      let payload: Record<string, unknown> | undefined;

      if (options.secret) {
        const secretKey = new TextEncoder().encode(options.secret);
        const result = await jwtVerify(token, secretKey);
        payload = result.payload;
      } else if (remoteJwks) {
        const result = await jwtVerify(token, remoteJwks);
        payload = result.payload;
      }

      if (!payload) return null;

      const sub =
        typeof payload.sub === "string" && payload.sub.length > 0
          ? payload.sub
          : typeof payload.id === "string" && payload.id.length > 0
            ? payload.id
            : "mcp-user";

      const attributes: Record<string, unknown> = {};
      if (typeof payload.email === "string") attributes.email = payload.email;
      if (typeof payload.name === "string") attributes.name = payload.name;
      if (typeof payload.scope === "string") attributes.scope = payload.scope;
      if (typeof payload.role === "string") attributes.role = payload.role;

      return {
        id: sub,
        attributes: Object.freeze(attributes),
      };
    } catch {
      // Fail closed: invalid token, signature failure, or expiration returns null
      return null;
    }
  }

  const resourceMetadata: McpHttpProtectedResourceMetadata = {
    resource: options.resourceUrl,
    authorizationServers: [options.authServerUrl],
    scopesSupported: supportedScopes,
  };

  return {
    mode: "required",
    resourceMetadata,
    challengeScopes: supportedScopes,
    async authenticate(request: McpHttpAuthenticationRequest) {
      const header = request.headers.get("authorization");
      if (header === null) return null;

      const match = /^Bearer\s+(\S+)$/i.exec(header.trim());
      if (match === null || match[1] === undefined) return null;

      return verifyJwt(match[1]);
    },
  };
}
