/**
 * Authentication hook for the MCP HTTP composition root.
 *
 * The adapter calls authenticate() for every request that passes the Host and
 * Origin checks. Return the principal the credential proves, or null to answer
 * with an HTTP 401 Bearer challenge. Verify the credential itself here: the
 * engine authorizes a principal, it does not authenticate one.
 *
 * Generated by "invokta-deploy init". This file is yours to edit.
 */
import { timingSafeEqual } from "node:crypto";
import { Buffer } from "node:buffer";

import type { McpHttpAuthOptions } from "@invokta/mcp";
import { EngineStartupError } from "./env.js";

type RequiredMcpHttpAuth = Extract<
  McpHttpAuthOptions,
  { readonly mode: "required" }
>;

const minimumTokenLength = 32;

function equalOpaqueValue(actual: string, expected: string): boolean {
  const actualBytes = Buffer.from(actual, "utf8");
  const expectedBytes = Buffer.from(expected, "utf8");
  return (
    actualBytes.length === expectedBytes.length &&
    timingSafeEqual(actualBytes, expectedBytes)
  );
}

/** Creates fail-closed bearer authentication for the MCP HTTP endpoint. */
export function createHttpAuth(expectedToken: string): RequiredMcpHttpAuth {
  if (expectedToken.length < minimumTokenLength) {
    throw new EngineStartupError(
      `MCP_BEARER_TOKEN must contain at least ${minimumTokenLength} characters.`,
    );
  }
  const expectedCredential = `Bearer ${expectedToken}`;

  return {
    mode: "required",
    authenticate(request) {
      const credential = request.headers.get("authorization");
      if (credential === null) return null;
      return equalOpaqueValue(credential, expectedCredential)
        ? { id: "mcp-client" }
        : null;
    },
  };
}
