/**
 * MCP Streamable HTTP composition root.
 *
 * Configuration comes from the environment only:
 *
 *   INVOKTA_HTTP_HOST             bind host (default 127.0.0.1)
 *   INVOKTA_HTTP_PORT, PORT       bind port (default 3000); the Invokta-specific
 *                                   name wins when both are set
 *   INVOKTA_HTTP_ALLOWED_HOSTS    comma-separated Host allowlist, required
 *                                   for a non-loopback bind
 *   INVOKTA_HTTP_ALLOWED_ORIGINS  comma-separated browser origin allowlist
 *   INVOKTA_HTTP_MAX_BODY_BYTES   request body limit (adapter default 1 MiB)
 *
 * An invalid value aborts startup rather than falling back to a default, and
 * every diagnostic goes to stderr without any value.
 *
 * Generated by "invokta-deploy init". This file is yours to edit.
 */
// Keep this import first and on its own: importing the loader applies the
// environment file, and nothing below may read configuration before it has.
import "./env.js";

import { serveMcpHttp } from "@invokta/mcp";

import {
  EngineStartupError,
  reportStartupFailure,
  requireEnvironment,
} from "./env.js";
import { reportConnectorConfigurationFailure } from "./openapi/startup.js";

const requiredEnvironmentNames = [
  "MCP_BEARER_TOKEN",
  "SPEDY_API_KEY",
  "SPEDY_BASE_URL",
] as const;

const defaultHost = "127.0.0.1";
const defaultPort = 3000;
const maximumPort = 65_535;
const loopbackHosts = new Set(["127.0.0.1", "localhost", "::1", "[::1]"]);
const nulCharacter = "\u0000";

function readValue(name: string): string | undefined {
  const value = process.env[name];
  if (value === undefined) return undefined;
  if (value === "") {
    throw new EngineStartupError(`${name} must not be empty.`);
  }
  if (value.includes(nulCharacter)) {
    throw new EngineStartupError(`${name} must not contain a NUL character.`);
  }
  return value;
}

/** Splits on commas, trims every item, and drops the empty ones. */
function readList(name: string): readonly string[] | undefined {
  const value = readValue(name);
  if (value === undefined) return undefined;
  const items = value
    .split(",")
    .map((item) => item.trim())
    .filter((item) => item !== "");
  if (items.length === 0) {
    throw new EngineStartupError(`${name} must list at least one entry.`);
  }
  return items;
}

function readInteger(
  name: string,
  minimum: number,
  maximum: number,
): number | undefined {
  const value = readValue(name);
  if (value === undefined) return undefined;
  const parsed = /^[0-9]+$/.test(value) ? Number(value) : Number.NaN;
  if (!Number.isSafeInteger(parsed) || parsed < minimum || parsed > maximum) {
    throw new EngineStartupError(
      `${name} must be an integer between ${minimum} and ${maximum}.`,
    );
  }
  return parsed;
}

async function main(): Promise<void> {
  requireEnvironment(requiredEnvironmentNames);

  const host = readValue("INVOKTA_HTTP_HOST") ?? defaultHost;
  const port =
    readInteger("INVOKTA_HTTP_PORT", 0, maximumPort) ??
    readInteger("PORT", 0, maximumPort) ??
    defaultPort;
  const allowedHosts = readList("INVOKTA_HTTP_ALLOWED_HOSTS");
  const allowedOrigins = readList("INVOKTA_HTTP_ALLOWED_ORIGINS");
  const maxRequestBodyBytes = readInteger(
    "INVOKTA_HTTP_MAX_BODY_BYTES",
    1,
    Number.MAX_SAFE_INTEGER,
  );

  // The adapter validates the raw Host header, so a non-loopback bind cannot
  // be served without an explicit allowlist.
  if (allowedHosts === undefined && !loopbackHosts.has(host)) {
    throw new EngineStartupError(
      "INVOKTA_HTTP_ALLOWED_HOSTS is required when INVOKTA_HTTP_HOST is not a loopback address.",
    );
  }

  // Imported here so nothing is constructed before the configuration is known
  // to be complete. Adjust the path when the engine is not exported from
  // src/engine.ts.
  const { createHttpAuth } = await import("./http-auth.js");
  const { engine } = await import("./engine.js");
  const bearerToken = readValue("MCP_BEARER_TOKEN");
  if (bearerToken === undefined) {
    throw new EngineStartupError("MCP_BEARER_TOKEN is required.");
  }

  const server = await serveMcpHttp(engine, {
    host,
    port,
    ...(allowedHosts === undefined ? {} : { allowedHosts }),
    ...(allowedOrigins === undefined ? {} : { allowedOrigins }),
    ...(maxRequestBodyBytes === undefined ? {} : { maxRequestBodyBytes }),
    auth: createHttpAuth(bearerToken),
  });

  let closing = false;
  const shutdown = (): void => {
    if (closing) return;
    closing = true;
    // ADR 0007 bounds close(): tracked requests are aborted and connections
    // are closed, so the process ends without a drain timeout of its own.
    server.close().then(
      () => process.exit(0),
      () => process.exit(1),
    );
  };
  // Registered before the announcement: the announcement is what tells a
  // supervisor the process is up, and a signal arriving before these handlers
  // exist would terminate it by default disposition instead of closing it.
  process.once("SIGTERM", shutdown);
  process.once("SIGINT", shutdown);

  const address = server.address();
  process.stderr.write(
    `MCP endpoint: http://${address.host}:${address.port}/mcp\n`,
  );
}

try {
  await main();
} catch (error) {
  if (!reportConnectorConfigurationFailure(error)) {
    reportStartupFailure(error);
  }
}
